run-yolo-demo:
	python scripts/basic-image/yolo-demo.py ./model/yolov8n.pt ./data/crowd.jpeg

run-onnx-demo-gpu:
	python scripts/basic-image/onnx_demo.py ./model/yolov8n.onnx ./data/crowd.jpeg --use-gpu true
