macro(install_headers)
foreach(header ${ARGN})
    get_filename_component(header_dir ${header} DIRECTORY)
    install(FILES ${header} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${header_dir})
endforeach(header ${ARGN})
endmacro()

macro(SUB_DIR_LIST result curdir)
  file(GLOB children ${curdir}/*)
  set(dirlist "")
  foreach(child ${children})
    if(IS_DIRECTORY ${child})
      get_filename_component(dir_name ${child} NAME_WE)
      list(APPEND dirlist ${dir_name})
    endif()
  endforeach()
  set(${result} ${dirlist})
endmacro()
